namespace Spike.Desktop;

public static partial class Text
{
    private static readonly Dictionary<string, string[]> ActivityStrings = new()
    {
        ["activities"] = ["Activités", "Activities", "Actividades"],
        ["activitiesIntro"] = ["Votre prochaine activité, vos objectifs du jour. Tout reste sur ce PC.", "Your next event, your goals for today. Everything stays on this PC.", "Tu próximo evento, tus objetivos de hoy. Todo se queda en este PC."],
        ["checklist"] = ["Checklist", "Checklist", "Lista de tareas"],
        ["schedule"] = ["Événements & rappels", "Events & reminders", "Eventos y avisos"],
        ["daily"] = ["Quotidien", "Daily", "Diario"],
        ["weekly"] = ["Hebdomadaire", "Weekly", "Semanal"],
        ["mainCharacter"] = ["Personnage principal", "Main character", "Personaje principal"],
        ["checklistProgress"] = ["{0} / {1} objectifs terminés", "{0} / {1} goals complete", "{0} / {1} objetivos completados"],
        ["nextReset"] = ["Reset {0} · dans {1} · heure locale", "Reset {0} · in {1} · local time", "Reinicio {0} · en {1} · hora local"],
        ["emptyChecklist"] = ["Aucune tâche visible. Personnalisez votre liste depuis Activités.", "No visible tasks. Customize your list in Activities.", "No hay tareas visibles. Personaliza tu lista en Actividades."],
        ["manualChecklist"] = ["Cochez vous-même vos objectifs. Les compteurs et les personnages sont indépendants du combat détecté.", "Check off your own goals. Counters and characters are independent of captured combat.", "Marca tus objetivos manualmente. Los contadores y personajes son independientes del combate detectado."],
        ["customizeChecklist"] = ["Personnaliser ma checklist", "Customize my checklist", "Personalizar mi lista"],
        ["customizeHint"] = ["Affichez les tâches utiles et ajustez leur objectif (1–999). Une tâche masquée conserve son suivi. Les tâches sont communes, les compteurs sont propres à chaque personnage.", "Show useful tasks and adjust their goal (1–999). Hidden tasks retain their progress. Tasks are shared; each character has separate counters.", "Muestra las tareas útiles y ajusta su objetivo (1–999). Las tareas ocultas conservan su progreso. Las tareas se comparten; cada personaje tiene sus contadores."],
        ["selectedPeriod"] = ["Période sélectionnée", "Selected period", "Período seleccionado"],
        ["goal"] = ["Objectif", "Goal", "Objetivo"],
        ["goalError"] = ["Saisissez un objectif entre 1 et 999.", "Enter a goal from 1 to 999.", "Introduce un objetivo de 1 a 999."],
        ["addTask"] = ["Ajouter une tâche", "Add a task", "Añadir una tarea"],
        ["taskName"] = ["Nom de la tâche", "Task name", "Nombre de la tarea"],
        ["addCharacter"] = ["Ajouter un personnage", "Add a character", "Añadir un personaje"],
        ["increase"] = ["Ajouter une réalisation", "Add one completion", "Añadir una realización"],
        ["decrease"] = ["Retirer une réalisation", "Remove one completion", "Restar una realización"],
        ["localSchedule"] = ["Vos prochains rendez-vous", "Your next events", "Tus próximos eventos"],
        ["scheduleEvidence"] = ["Horaires Global · sources consultées le 6 octobre 2026. Les horaires communautaires peuvent changer. Vérifiez-les en jeu ; chaque événement est modifiable.", "Global schedules · sources checked 6 October 2026. Community schedules may change. Check in game; every event can be edited.", "Horarios Global · fuentes consultadas el 6 de octubre de 2026. Los horarios comunitarios pueden cambiar. Compruébalos en el juego; cada evento es editable."],
        ["referenceClock"] = ["Référence", "Reference", "Referencia"],
        ["community"] = ["Horaire communautaire", "Community schedule", "Horario comunitario"],
        ["uncertain"] = ["À confirmer en jeu", "Confirm in game", "Por confirmar en el juego"],
        ["custom"] = ["Horaire personnalisé", "Custom schedule", "Horario personalizado"],
        ["source"] = ["Source", "Source", "Fuente"],
        ["edit"] = ["Modifier", "Edit", "Editar"],
        ["notifyMe"] = ["Me rappeler", "Remind me", "Avisarme"],
        ["enableReminders"] = ["Activer les notifications d’événements", "Enable event notifications", "Activar avisos de eventos"],
        ["reminderHint"] = ["Une notification discrète pour les événements cochés, même si Spike est minimisé ou la capture arrêtée. Gardez la fenêtre principale ouverte. Les rappels cessent à sa fermeture ; le plein écran exclusif peut les masquer.", "A discreet notification for selected events, even when Spike is minimized or capture is stopped. Keep the main window open. Closing it stops reminders; exclusive fullscreen may hide them.", "Un aviso discreto para los eventos seleccionados, incluso con Spike minimizado o la captura detenida. Mantén abierta la ventana principal. Al cerrarla se detienen los avisos; la pantalla completa exclusiva puede ocultarlos."],
        ["notificationSound"] = ["Jouer un son avec le rappel", "Play a reminder sound", "Reproducir un sonido con el aviso"],
        ["leadMinutes"] = ["Prévenir avant (0–60 minutes ; 0 = à l’heure)", "Warn before (0–60 minutes; 0 = at start)", "Avisar antes (0–60 minutos; 0 = al empezar)"],
        ["utcOffset"] = ["Fuseau des horaires saisis (décalage UTC fixe)", "Time zone for entered schedules (fixed UTC offset)", "Zona horaria de los horarios introducidos (desfase UTC fijo)"],
        ["resetTime"] = ["Heure du reset quotidien (HH:mm)", "Daily reset time (HH:mm)", "Hora de reinicio diario (HH:mm)"],
        ["weeklyDay"] = ["Jour du reset hebdomadaire", "Weekly reset day", "Día de reinicio semanal"],
        ["resetEvidence"] = ["Préréglage Global : événements en UTC, reset à 07:00 UTC, le mercredi pour la semaine (AION2 Hub). Les guides divergent : ajustez selon votre serveur. Changer le fuseau déplace tous les horaires saisis ; changer le reset recalcule les compteurs. L’affichage local suit l’heure d’été.", "Global preset: events in UTC, reset at 07:00 UTC, Wednesday for the week (AION2 Hub). Guides disagree: adjust for your server. Changing the time zone moves all entered schedules; changing the reset recalculates counters. Local display follows daylight saving time.", "Preajuste Global: eventos en UTC, reinicio a las 07:00 UTC, los miércoles para la semana (AION2 Hub). Las guías difieren: ajústalo a tu servidor. Cambiar la zona horaria desplaza los horarios; cambiar el reinicio recalcula los contadores. La hora local sigue el horario de verano."],
        ["scheduleError"] = ["Vérifiez le délai (0–60), l’heure (HH:mm), le fuseau et le jour.", "Check the lead time (0–60), time (HH:mm), time zone and day.", "Comprueba el aviso (0–60), la hora (HH:mm), la zona horaria y el día."],
        ["reminderSettings"] = ["Délai, son et horaires de reset", "Lead time, sound and reset times", "Antelación, sonido y reinicios"],
        ["testNotification"] = ["Tester une notification", "Test a notification", "Probar un aviso"],
        ["testNotificationBody"] = ["Vos rappels apparaîtront ici. Bonne session !", "Your reminders will appear here. Enjoy your session!", "Tus avisos aparecerán aquí. ¡Disfruta de la sesión!"],
        ["moreEvents"] = ["+ {0} autres événements", "+ {0} more events", "+ {0} eventos más"],
        ["startsIn"] = ["dans {0} min", "in {0} min", "en {0} min"],
        ["openActivities"] = ["Ouvrir les activités", "Open activities", "Abrir actividades"],
        ["dismissReminder"] = ["Fermer le rappel", "Dismiss reminder", "Cerrar aviso"],
        ["returnToMeter"] = ["Revenir au compteur", "Return to meter", "Volver al medidor"],
        ["addEvent"] = ["Ajouter un événement", "Add an event", "Añadir un evento"],
        ["editEvent"] = ["Modifier l’événement", "Edit event", "Editar evento"],
        ["eventName"] = ["Nom de l’événement", "Event name", "Nombre del evento"],
        ["eventTimes"] = ["Horaires HH:mm séparés par des virgules", "HH:mm times separated by commas", "Horas HH:mm separadas por comas"],
        ["eventError"] = ["Indiquez un nom, 1 à 24 horaires HH:mm et au moins un jour.", "Enter a name, 1 to 24 HH:mm times and at least one day.", "Introduce un nombre, de 1 a 24 horas HH:mm y al menos un día."],
        ["checklistLimit"] = ["La limite de 100 tâches est atteinte.", "The limit of 100 tasks has been reached.", "Se ha alcanzado el límite de 100 tareas."],
        ["characterLimit"] = ["La limite de 20 personnages est atteinte.", "The limit of 20 characters has been reached.", "Se ha alcanzado el límite de 20 personajes."],
        ["activityLimit"] = ["La limite de 100 événements est atteinte.", "The limit of 100 events has been reached.", "Se ha alcanzado el límite de 100 eventos."],
        ["cancelActivity"] = ["Annuler", "Cancel", "Cancelar"],
        ["deleteActivity"] = ["Supprimer cet événement", "Delete this event", "Eliminar este evento"],
        ["activitiesLoadError"] = ["La sauvegarde des activités est illisible. Le fichier activities.json est conservé et ne sera pas écrasé. Corrigez-le ou renommez-le dans le dossier Spike, puis relancez l’application.", "The activities save cannot be read. The activities.json file is preserved and will not be overwritten. Fix or rename it in the Spike folder, then restart the app.", "No se puede leer el archivo de actividades. Se conserva activities.json y no se sobrescribirá. Corrígelo o cámbiale el nombre en la carpeta Spike y reinicia la aplicación."],
        ["eventShugo"] = ["Festival Shugo", "Shugo Festival", "Festival Shugo"],
        ["eventRift"] = ["Faille spatio-temporelle", "Spacetime Rift", "Grieta espaciotemporal"],
        ["eventSiege"] = ["Siège des artefacts", "Artifact Siege", "Asedio de artefactos"],
        ["eventSiegeBosses"] = ["Boss de siège", "Siege Bosses", "Jefes de asedio"],
        ["eventNahma"] = ["Général gardien Nahma", "Guardian General Nahma", "General guardián Nahma"],
        ["eventKaira"] = ["Guetteur Kaira", "Watcher Kaira", "Vigía Kaira"],
        ["eventInvasion"] = ["Invasion dimensionnelle", "Dimensional Invasion", "Invasión dimensional"],
        ["taskQuests"] = ["Quêtes du jour", "Daily quests", "Misiones del día"],
        ["taskShugo"] = ["Participations au Festival Shugo", "Shugo Festival entries", "Participaciones en el Festival Shugo"],
        ["taskNightmare"] = ["Boss de Nightmare", "Nightmare bosses", "Jefes de Nightmare"],
        ["taskOdyle"] = ["Dépenser mon Odyle en donjons", "Spend my Odyle in dungeons", "Gastar mi Odyle en mazmorras"],
        ["taskAbyss"] = ["Contrats des Abysses", "Abyss contracts", "Contratos del Abismo"],
        ["taskAltgard"] = ["Contrats d’Altgard", "Altgard contracts", "Contratos de Altgard"],
        ["taskCraft"] = ["Recharges d’Odyle : artisanat", "Odyle refills: crafting", "Recargas de Odyle: fabricación"],
        ["taskBuy"] = ["Recharges d’Odyle : marchand", "Odyle refills: merchant", "Recargas de Odyle: mercader"],
        ["taskDungeons"] = ["Entrées en donjons quotidiens", "Daily dungeon entries", "Entradas en mazmorras diarias"],
        ["taskTickets"] = ["Tickets de complétion instantanée", "Instant clear tickets", "Tickets de finalización instantánea"],
        ["taskSeason"] = ["Objectifs de saison hebdomadaires", "Weekly season objectives", "Objetivos semanales de temporada"],
        ["taskTrophies"] = ["Atteindre 11 000 trophées", "Reach 11,000 trophies", "Alcanzar 11 000 trofeos"],
        ["taskAscension"] = ["Épreuve d’Ascension", "Ascension Trial", "Prueba de Ascensión"],
    };
}
