<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="DPSMeter.EngineChecks" />
    <ProjectReference Include="../DPSMeter.Core/DPSMeter.Core.csproj" />
    <PackageReference Include="SharpPcap" Version="6.3.1" />
    <PackageReference Include="PacketDotNet" Version="1.4.8" />
    <EmbeddedResource Include="assets/**/*.json" LogicalName="assets/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
